---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./src/*/*.ts"
postMerge:
  pattern:
    - "./src/*/*.ts"
postRun:
     command:
        - yarn --version
version: 1.0
